# Generated by Django 2.2.6 on 2019-10-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.TextField()),
                ('customer_id', models.TextField(primary_key=True, serialize=False)),
                ('accounting_contact', models.TextField()),
                ('technical_contact', models.TextField()),
                ('distributor_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webapp',
            fields=[
                ('system_name', models.TextField(primary_key=True, serialize=False)),
                ('product', models.TextField()),
                ('super_admin', models.TextField()),
                ('url', models.URLField()),
                ('drive', models.URLField()),
                ('max_users', models.IntegerField()),
                ('organizationID', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.TextField(default='Some generated text')),
                ('service_start_date', models.DateField()),
                ('service_end_date', models.DateField()),
                ('service_duration', models.IntegerField()),
                ('status', models.BooleanField()),
                ('product_type', models.TextField()),
                ('service_type', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Customer')),
                ('system_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display.Webapp')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('gateway_id', models.TextField(primary_key=True, serialize=False)),
                ('refresh_rate', models.FloatField()),
                ('uid_list', models.TextField()),
                ('system', models.TextField()),
                ('IMEI_MAC', models.TextField()),
                ('firmware_upgrade', models.TextField()),
                ('moblie_number', models.TextField()),
                ('max_sms', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Tag'),
        ),
    ]
