# Generated by Django 2.2.6 on 2019-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accounting_contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='technical_contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='accounting_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='accounting_phone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='technical_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='technical_phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='distributor_name',
            field=models.TextField(null=True),
        ),
    ]
