# Generated by Django 2.2.6 on 2019-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20191111_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accounting_name',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounting_phone',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='distributor_name',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='technical_name',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='technical_phone',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
