# Generated by Django 2.2.6 on 2019-11-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20191111_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='accounting_phone',
            new_name='accounting_contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='technical_phone',
            new_name='technical_contact',
        ),
    ]
