# Generated by Django 2.2.6 on 2019-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20191111_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webapp',
            name='super_admin',
        ),
        migrations.AddField(
            model_name='webapp',
            name='super_admin_id',
            field=models.TextField(default='asgsg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapp',
            name='super_admin_password',
            field=models.TextField(default='asfasf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webapp',
            name='drive',
            field=models.URLField(blank=True, default='-'),
        ),
    ]
