# Generated by Django 2.2.6 on 2019-11-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20191112_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='webapp',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='IMEI_MAC',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='firmware_upgrade',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='max_sms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='moblie_number',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='refresh_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='system',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='uid_list',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
