# Generated by Django 2.2.6 on 2019-11-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_auto_20191112_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='system',
        ),
        migrations.RemoveField(
            model_name='service',
            name='SKU',
        ),
        migrations.AddField(
            model_name='gateway',
            name='system_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounting_contact',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accounting_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='distributor_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='technical_contact',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='technical_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='IMEI_MAC',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='firmware_upgrade',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='moblie_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='uid_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='drive',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
