# Generated by Django 2.2.6 on 2019-11-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20191114_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='max_sms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='refresh_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='system_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='system_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.Webapp'),
        ),
    ]
