# Generated by Django 2.2.6 on 2019-11-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20191116_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
