# Generated by Django 2.2.6 on 2019-11-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20191116_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='product_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
